name: Intel (classic) Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: MPI = TRUE, OPT = FALSE, DEBUG = FALSE
    env:
      CHOMBO_HOME: ${{ github.workspace}}/Chombo/lib
      OMP_NUM_THREADS: 1
      BUILD_ARGS: MPI=TRUE OPT=FALSE DEBUG=TRUE

    steps:

      - name: Checkout Chombo from GRTLCollaboration
        uses: actions/checkout@master
        with:
          repository: GRTLCollaboration/Chombo
          token: ${{ secrets.CI_SECRET || github.token }}
          path: Chombo

      - name: Checkout GRChombo from GRTLCollaboration
        uses: actions/checkout@master
        with:
          repository: GRTLCollaboration/GRChombo
          token: ${{ secrets.CI_SECRET || github.token }}
          path: GRChombo

      - name: Update package manager database
        id: update-database
        continue-on-error: true
        run: sudo apt-get update

      - name: Update package repository mirrors if necessary
        if: steps.update-database.outcome == 'failure'
        run: |
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          sudo apt-get update

      - name: Install Chombo dependencies
        run: sudo apt-get -y --no-install-recommends install csh libgetopt-complete-perl

      - name: Install Intel Compilers
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get -y install intel-basekit
        working-directory: /tmp

      - name: Install Intel MPI
        if: matrix.mpi == 'TRUE'
        run: |
          sudo apt-get -y install intel-oneapi-mpi intel-oneapi-mpi-devel

      - name: Build Chombo
        run: |
          source /opt/intel/oneapi/setvars.sh
          cp $GITHUB_WORKSPACE/GRChombo/InstallNotes/MakeDefsLocalExamples/intel-classic-no-hdf5-minimal.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
          make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools $BUILD_ARGS
        working-directory: ${{ env.CHOMBO_HOME }}
        
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build GRChombo Tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          make test -j 4 $BUILD_ARGS
        working-directory: ${{ github.workspace }}/GRChombo

      - name: Run GRChombo Tests
        run: |
          source /opt/intel/oneapi/setvars.sh
          make run -j 2 $BUILD_ARGS
        working-directory: ${{ github.workspace }}/GRChombo


        
